import sys
from sys import argv
import argparse
from pathlib import Path

from utils import write_to_file
from LS1_hillclimb import hc

if __name__=="__main__":
    '''
    Sample command: python main.py --inst email.graph --alg ls1 --time 600 --seed 10
    The implemented algorithms are Branch & Bound (bnb), Approximation (approx), Hill Climbing (ls1) and ...  
    The available instances are:
    1. as-22july06.graph
    2. delaunay_n10.graph
    3. dummy1.graph
    4. email.graph
    5. football.graph
    6. help-th.graph
    7. jazz.graph
    8. karate.graph
    9. netscience.graph
    10. power.graph
    11. star.graph
    12. star2.graph
    To run the procedure on all the sample graphs, simply provide the argument as "all" to --inst.
    '''

    parser = argparse.ArgumentParser(description='Different algorithms to compute the VC of a graph')
    parser.add_argument('--inst',action='store',type=str,required=True,help='Instance of graph')
    parser.add_argument('--alg',action='store',type=str,required=True,help='Type of algorithm - (BnB,Approx,LS1 (Hill climbing),...)')
    parser.add_argument('--time',action='store',default=600,type=int,required=True,help='Maximum runtime (s)')
    parser.add_argument('--seed',action='store',default=10,type=int,required=False,help='Random Seed')
    args=parser.parse_args()    
    filename,alg,maxtime,seed = args.inst,args.alg,args.time,args.seed

    allowed_inst = ["email.graph","as-22july06.graph","delaunay_n10.graph","dummy1.graph","football.graph",
    "hep-th.graph","jazz.graph","karate.graph","netscience.graph","power.graph","star.graph","star2.graph"]
    
    if alg.lower() == "ls1":
        if filename=='all':
            for inst in allowed_inst:
                file_check = Path("results/"+inst+"_"+alg.upper()+"_"+str(maxtime)+"_"+str(seed)+".sol")
                if file_check.is_file():
                    print("Solution already generated. Continuing...")
                    continue
                VC,solTrace = hc(inst,maxtime,seed)
                print("VC for "+inst+" generated by hill-climbing algorithm")
                write_to_file(VC,inst,"LS1",maxtime,seed,solTrace)
        else:
            VC,solTrace = hc(filename,maxtime,seed)
            print("VC for "+filename+" generated by hill-climbing algorithm")
            write_to_file(VC,filename,"LS1",maxtime,seed,solTrace)